/**
 * @file users.js
 * @description Local fallback database for user authentication and access control.
 */

export const users = [
  {
    email: 'ibrahim@example.local',
    username: 'ibrahim',
    password: '123',
    name: 'إبراهيم الجملة (أبو كريم)',
    fullName: 'إبراهيم الجملة (أبو كريم)',
    role: 'admin',
    governorate: 'all',
    active: true,
    showHome: true,
    showStats: true,
    showFlow: true,
    showStyle: true,
    showPersonas: true,
    canDraw: true,
    canEditData: true,
    canEditStatus: true,
    canExport: true,
    canManageUsers: true,
    canEditGeometry: true,
    canDeleteGeometry: true
  },
  {
    email: 'ebahtity@example.local',
    username: 'ebahtity',
    password: '123',
    name: 'م. إيهاب البحتيطي',
    fullName: 'م. إيهاب البحتيطي',
    role: 'viewer',
    governorate: ['غزة', 'شمال غزة'],
    active: true,
    showHome: true,
    showStats: true,
    showFlow: true,
    showStyle: true,
    showPersonas: true
  },
  {
    email: 'neholy@example.local',
    username: 'neholy',
    password: '123',
    name: 'م. نهاد الحولي',
    fullName: 'م. نهاد الحولي',
    role: 'viewer',
    governorate: 'شمال غزة',
    active: true,
    showHome: true,
    showStats: true,
    showFlow: true,
    showStyle: true,
    showPersonas: true
  },
  {
    email: 'ahamad@example.local',
    username: 'ahamad',
    password: '123',
    name: 'م. عبدالمجيد حمد',
    fullName: 'م. عبدالمجيد حمد',
    role: 'viewer',
    governorate: 'غزة',
    active: true,
    showHome: true,
    showStats: true,
    showFlow: true,
    showStyle: true,
    showPersonas: true
  },
  {
    email: 'mjarad@example.local',
    username: 'mjarad',
    password: '123',
    name: 'م. محمود أبو جراد',
    fullName: 'م. محمود أبو جراد',
    role: 'viewer',
    governorate: 'غزة',
    active: true,
    showHome: true,
    showStats: true,
    showFlow: true,
    showStyle: true,
    showPersonas: true
  },
  {
    email: 'jalkass@example.local',
    username: 'jalkass',
    password: '123',
    name: 'م. جمال أبو الكاس',
    fullName: 'م. جمال أبو الكاس',
    role: 'viewer',
    governorate: ['غزة', 'شمال غزة'],
    active: true,
    showHome: true,
    showStats: true,
    showFlow: true,
    showStyle: true,
    showPersonas: true
  },
  {
    email: 'ehouda@example.local',
    username: 'ehouda',
    password: '123',
    name: 'م. إيهاب أبو عودة',
    fullName: 'م. إيهاب أبو عودة',
    role: 'viewer',
    governorate: ['غزة', 'شمال غزة'],
    active: true,
    showHome: true,
    showStats: true,
    showFlow: true,
    showStyle: true,
    showPersonas: true
  }
];
